#!/usr/bin/env bash
set -e

rm -rf /out/*

meson setup --buildtype=release --prefix=/usr builddir
ninja -C builddir
cp -r builddir /out/

ASFLAGS=--32 CFLAGS=-m32 CXXFLAGS=-m32 PKG_CONFIG_PATH=/usr/lib32/pkgconfig meson setup --prefix=/usr --buildtype=release --libdir=lib32 -Dwith_json=false builddir.32
ninja -C builddir.32
cp -r builddir.32 /out/